{% set name = "tobler" %}
{% set version = "0.5.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pysal/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 2c902fe2b708b9d6e8bbf461c25b8b9eb0d70f52ea88f560ace6a1a4267a5965

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python >=3.5
    - pip
    - setuptools
    - wheel
  run:
    - python >=3.5
    - numpy
    - pandas
    - geopandas
    - rasterio
    # <1.12 is because newer versions break the tests
    # ImportError: cannot import name 'inf' from 'scipy' -> inf is deprecated
    - scipy <1.12
    - statsmodels
    - rasterstats
    - libpysal
    - tqdm

test:
  source_files:
    - tobler/tests
    - test_dasymetric.py
  imports:
    - tobler
    - tobler.area_weighted
    - tobler.dasymetric
    - tobler.model
    - tobler.util
    - tobler.util.util
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest -v tobler/tests
    - pytest -v test_dasymetric.py
  requires:
    - pip
    - pytest

about:
  home: https://github.com/pysal/tobler
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Tobler is a python package for areal interpolation, dasymetric mapping, and change of support.
  description: |
    Tobler is a python package for areal interpolation, dasymetric mapping, and change of support.
  doc_url: https://pysal.org/tobler
  dev_url: https://github.com/pysal/tobler

extra:
  recipe-maintainers:
    - knaaptime
    - sjsrey
