{% set name = "tobler" %}
{% set version = "0.13.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8aac24aeb963151eb31cee6f24e6b9a83f7fc9ae0d4b92f08d7716308861ede9

build:
  number: 0
  skip: true  # [py<311]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv

requirements:
  host:
    - python
    - pip
    - setuptools >=61.0
    - setuptools_scm >=6.2
    # setuptools_scm[toml]
    - toml
    - wheel
  run:
    - python
    - geopandas >=1.0
    - joblib >=1.4
    - libpysal >=4.10
    - numpy >=2.0
    - pandas >=2.2
    - rasterio >=1.4
    - rasterstats >=0.20
    - scipy >=1.13
    - statsmodels >=0.14
    - tqdm >=4.67

# =======================
# Test configuration
# =======================
{% set test_root = "tobler/tests" %}

# - test_area_interpolators: require dask_geopandas
# - test_utils: require h3
{% set skip_files = [
    "tobler/tests/test_area_interpolators.py",
    "tobler/tests/test_utils.py"
] %}

# - test_masked_area_interpolate, test_glm_poisson: too long execution
# - test_pycno_interpolate, test_custom_index: require astropy 
{% set skip_keywords = [
    "test_masked_area_interpolate",
    "test_glm_poisson",
    "test_pycno_interpolate",
    "test_custom_index"
] %}

test:
  requires:
    - pip
    - pytest
    # bypass a test-only issue introduced with pandas versions >=3.0
    # E       AssertionError: assert <StringDtype(storage='python', na_value=nan)> == object
    - pandas <3.0
  source_files:
    - {{ test_root }}
  imports:
    - tobler
    - tobler.area_weighted
    - tobler.area_weighted.area_interpolate
    - tobler.dasymetric
    - tobler.model
    - tobler.pycno
    - tobler.util
    - tobler.util.util
  commands:
    - pip check
    - pytest -v {{ test_root }}{% for file in skip_files %} --ignore={{ file }}{% endfor %} -k "not ({{ skip_keywords | join(' or ') }})"

about:
  home: https://github.com/pysal/tobler
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Tobler is a python package for areal interpolation, dasymetric mapping, and change of support.
  description: |
    Tobler is a python package for areal interpolation, dasymetric mapping, and change of support.
  doc_url: https://pysal.org/tobler
  dev_url: https://github.com/pysal/tobler

extra:
  recipe-maintainers:
    - knaaptime
    - sjsrey
