{% set name = "tobler" %}
{% set version = "0.12.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 96a05c2bd69569c5fadb940f7ad242dd8a43d12c7818c7ab97534e46670677f1

build:
  number: 0
  # Skip Python <3.10 due to libpysal <4.10 (noarch) causing import errors with scipy >=1.8.0
  skip: true  # [py<310]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv

requirements:
  host:
    - python
    - pip
    - setuptools
    - setuptools_scm >=6.2
    - wheel
  run:
    - python
    - numpy
    - pandas
    - geopandas >=0.13
    - rasterio
    - scipy
    - statsmodels
    - rasterstats
    # libpysal <4.10 is incompatible with scipy >=1.8.0 and leads to import errors
    # See scipy 1.8.0 release notes for details
    - libpysal >=4.10
    - tqdm
    - joblib

# =======================
# Test configuration
# =======================
{% set test_root = "tobler/tests" %}

# - test_area_interpolators: require dask_geopandas
# - test_utils: require h3
{% set skip_files = [
    "tobler/tests/test_area_interpolators.py",
    "tobler/tests/test_utils.py"
] %}

# - test_masked_area_interpolate, test_glm_poisson: too long execution
# - test_pycno_interpolate, test_custom_index: require astropy 
{% set skip_keywords = [
    "test_masked_area_interpolate",
    "test_glm_poisson",
    "test_pycno_interpolate",
    "test_custom_index"
] %}

test:
  requires:
    - pip
    - pytest
  source_files:
    - {{ test_root }}
  imports:
    - tobler
    - tobler.area_weighted
    - tobler.area_weighted.area_interpolate
    - tobler.dasymetric
    - tobler.model
    - tobler.pycno
    - tobler.util
    - tobler.util.util
  commands:
    - pip check
    - pytest -v {{ test_root }}{% for file in skip_files %} --ignore={{ file }}{% endfor %} -k "not ({{ skip_keywords | join(' or ') }})"

about:
  home: https://github.com/pysal/tobler
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Tobler is a python package for areal interpolation, dasymetric mapping, and change of support.
  description: |
    Tobler is a python package for areal interpolation, dasymetric mapping, and change of support.
  doc_url: https://pysal.org/tobler
  dev_url: https://github.com/pysal/tobler

extra:
  recipe-maintainers:
    - knaaptime
    - sjsrey
