{% set name = "tobler" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5ce999674e2e442c2fe4de3e498550d699c608257ede2ac2fd2f8ad37a5d0f50

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - python-dateutil <=2.8.0
    - pandas
    - numpy >=1.16
    - geopandas
    - rasterio
    - rasterstats
    - statsmodels
    - scipy
    - libpysal >=4.2.0
    - quilt3 >=3.1.11
    - tqdm

test:
  imports:
    - tobler

about:
  home: https://github.com/pysal/tobler
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Tobler is a python package for areal interpolation, dasymetric mapping, and change of support.
  description: |
    Tobler is a python package for areal interpolation, dasymetric mapping, and change of support.
  doc_url: https://pysal.org/tobler/
  dev_url: https://github.com/pysal/tobler/

extra:
  recipe-maintainers:
    - knaaptime
    - sjsrey
